[OT267-39] endpoint de actualizacion de datos publicos de organizacion
alkemyTech/OT267-server pull request #38
Opened 2022-08-25 22:43 UTC by BrunoBohlmann

https://alkemy-labs.atlassian.net/jira/software/c/projects/OT267/boards/362?modal=detail&selectedIssue=OT267-39

<img width="775" alt="request" src="https://user-images.githubusercontent.com/80550062/186781362-88c57079-0fdc-4885-bfe0-c7fa9b4cb102.png">

2022-08-26 16:07 UTC, FerLeiva commented
Hola Bruno, la tarea pide que solamente el usuario administrador podrá editar los datos públicos de la Organización. Y que se deberán validar los campos requeridos y el formato correcto de los mismos.

Esto está chequeado? Donde sucede? Gracias!

2022-08-26 20:54 UTC, BrunoBohlmann commented
> Hola Bruno, la tarea pide que solamente el usuario administrador podrá editar los datos públicos de la Organización. Y que se deberán validar los campos requeridos y el formato correcto de los mismos.
> 
> Esto está chequeado? Donde sucede? Gracias!

Hola Fer,  me falto chequear y validar los campos del body? Si es asi, entonces es error mio. Pero te pregunto, entonces con chequear, ¿tendria q revisar que el numero de telefono sea uno en si? ¿tal vez utilizando expresiones regulares por ejemplo? Y con validar se refiere a estos mismos datos o a que sea admin el user? Disculpa que te pregunte estas cosas, pero las cards son poco explicitas creo.

2022-08-26 22:07 UTC, FerLeiva commented
Si! Hay que validar los campos enviados en el body para que coincidan con los requeridos. Asi es por ejemplo con regex podes validar el telefono y asi para todos los campos. Y en efecto, validar que el rol del user sea admin para poder hacer la actualizacion de los datos.

2022-08-27 01:44 UTC, BrunoBohlmann commented
Fer, fijate que en mi pull te van a figurar archivos nuevos, pero es solo que los renombre

2022-08-28 15:05 UTC, zayrarepositor requested changes
@BrunoBohlmann 

* faltan validar al menos 2 atributos requeridos: email y welcomeText. Tome como referecia models/organization

* hice un pull de tu rama a mi rama y, una vez verificado que estan tus cambios, al hacer el request post me da un error. Te dejo un screenshot

![postfailed](https://user-images.githubusercontent.com/95602965/187080271-19c62b06-b330-4167-a214-1decaf84badf.png)

@FerLeiva tengo una inquietud. Si la tarea es actualización de datos, por que se solicita una petición POST y no un PUT o PATCH?

2022-08-28 15:36 UTC, BrunoBohlmann commented
> @BrunoBohlmann
> 
> * faltan validar al menos 2 atributos requeridos: email y welcomeText. Tome como referecia models/organization
> * hice un pull de tu rama a mi rama y, una vez verificado que estan tus cambios, al hacer el request post me da un error. Te dejo un screenshot
> 
> ![postfailed](https://user-images.githubusercontent.com/95602965/187080271-19c62b06-b330-4167-a214-1decaf84badf.png)
> 
> @FerLeiva tengo una inquietud. Si la tarea es actualización de datos, por que se solicita una petición POST y no un PUT o PATCH?

Hola Zayra, ahi lo veo al error. Con respecto a tu consulta Fer, inicialmente hice un put, pero luego lei la card y explicitamente me pide un post, te lo iba a consultar porq obvio es un error, pero bueno. Por si acaso lo deje como post

2022-08-29 10:18 UTC, FerLeiva commented
Hola Bruno, no, inicialmente es un POST el que tenes que hacer ya que lo pide asi la tarea. Fijate si el error era porque tenias PUT, en ese caso corregilo y subi un screen de la peticion POST exitosa cuando quede! Gracias

2022-08-29 15:04 UTC, BrunoBohlmann commented
> Hola Bruno, no, inicialmente es un POST el que tenes que hacer ya que lo pide asi la tarea. Fijate si el error era porque tenias PUT, en ese caso corregilo y subi un screen de la peticion POST exitosa cuando quede! Gracias

Hola Fer, el error de Zayra es porque ella usa un post y es un put. Yo usando put funciona todo. Pero si asi lo requiere la taera lo hago post

2022-08-29 22:30 UTC, zayrarepositor approved these changes

2022-08-30 14:39 UTC, merged