feat: model, migration and basic controller for categorie
alkemyTech/OT267-server pull request #4
Opened 2022-08-20 18:11 UTC by FranciscoLynch

https://alkemy-labs.atlassian.net/jira/software/c/projects/OT267/boards/362?modal=detail&selectedIssue=OT267-19

2022-08-22 10:05 UTC, FerLeiva requested changes

2022-08-22 10:05 UTC, FerLeiva commented on seeders/20220820162211-create-demo-categorie.js
> +    /**
No dejar comentarios con codigo que no este en uso

2022-08-22 10:05 UTC, FerLeiva commented on seeders/20220820162211-create-demo-categorie.js
> +    /**
No dejar comentarios con codigo que no este en uso

2022-08-22 16:24 UTC, FranciscoLynch commented
Comentarios removidos

2022-08-23 15:16 UTC, FerLeiva approved these changes

2022-08-23 15:17 UTC, FerLeiva commented
Hola Fran, fiajte que tenes conflictos, por favor no commitees cosas como el .env, package.json, etc. Porfa volve a hacer el PR

2022-08-23 16:59 UTC, merged