[OT267-23] Crear modelo, migración y controlador base de Members
alkemyTech/OT267-server pull request #5
Opened 2022-08-20 18:46 UTC by FranciscoLynch

https://alkemy-labs.atlassian.net/jira/software/c/projects/OT267/boards/362?modal=detail&selectedIssue=OT267-23

2022-08-22 10:06 UTC, FerLeiva requested changes

2022-08-22 10:06 UTC, FerLeiva commented on seeders/20220820183835-create-demo-member.js
> +    /**
No dejar comentarios con codigo que no este en uso

2022-08-22 10:06 UTC, FerLeiva commented on seeders/20220820183835-create-demo-member.js
> +    /**
No dejar comentarios con codigo que no este en uso

2022-08-22 16:26 UTC, FranciscoLynch commented
Comentarios removidos

2022-08-23 15:04 UTC, FerLeiva approved these changes

2022-08-23 15:05 UTC, merged