[Ot267-57] Endpoint para almacenar contactos
alkemyTech/OT267-server pull request #65
Opened 2022-09-01 16:04 UTC by a-toro

Url: [Endpoint para almacenar contactos](https://alkemy-labs.atlassian.net/jira/software/c/projects/OT267/boards/362?modal=detail&selectedIssue=OT267-57)

> # Resumen
> Para crear el endpoint de almacenar los datos de contacto se realizó lo siguiente.
> -  Crear ruta para contactos /contacts.
> - Crear endpoint para registrar contactos con el méthodo POST.
> - Crear controller
> - Create services for register new contact.
> - Crear validarot, para validar que el nombre y email estén incluidos.

># Evidencia
>> ### Registro de contacto existoso.
>> <img width="634" alt="image" src="https://user-images.githubusercontent.com/77943203/187957615-f37dac58-3d25-46cd-ab9a-83a15a59959b.png">
>> <img width="641" alt="image" src="https://user-images.githubusercontent.com/77943203/187957668-121d0964-7fe8-4892-9eb9-425fe0c2bb9f.png">

>> ### Mensaje de error cuando el campo name esta vacío.
>> <img width="632" alt="image" src="https://user-images.githubusercontent.com/77943203/187959534-fcbe4663-47f2-4573-86c9-8e3349d73162.png">

>> ### Mensaje de error cuando el campo email no es ingresado correctamente.
>> <img width="628" alt="image" src="https://user-images.githubusercontent.com/77943203/187960006-f5da68ec-e276-4661-a844-c761096809e0.png">

2022-09-01 18:50 UTC, FerLeiva approved these changes

2022-09-01 18:51 UTC, FerLeiva commented
No te olvides de dejarme el link aca en un comentario porfa!

2022-09-02 14:21 UTC, a-toro commented
@FerLeiva ya realice la corrección de los conflictos con la rama main. @BrunoBohlmann por favor tu apoyo con la revisión del PR, de antemano muchas gracias por el apoyo.

2022-09-02 16:02 UTC, BrunoBohlmann requested changes
Hola William, fijate que los nombres sean mas descriptivos, el create en el controller por ejemplo

2022-09-02 17:20 UTC, a-toro commented
Buenas tardes @BrunoBohlmann , ya realice la correcciones del nombre de las funciones. Quedo atento si se requiere algún cambio adicional.

2022-09-03 01:29 UTC, BrunoBohlmann approved these changes
Aprobado!

2022-09-05 10:39 UTC, merged