[OT267-76] Endpoint Eliminación Miembros
alkemyTech/OT267-server pull request #73
Opened 2022-09-03 17:54 UTC by FranciscoLynch

Ticket: 
https://alkemy-labs.atlassian.net/jira/software/c/projects/OT267/boards/362?modal=detail&selectedIssue=OT267-76

Consulta para eliminar miembro
![memberRemoved](https://user-images.githubusercontent.com/81364315/188282430-755a73b1-4223-4c09-8a35-2c2e6122e0da.png)

Demostracion por consola(el console.log fue removido, solo fue aplicado para visualizar mejor el proceso de la consulta) 
![memberRemovedConsoleLog](https://user-images.githubusercontent.com/81364315/188282468-702fbb44-e52a-4f47-944a-d539ae0fb194.png)

Error al no encontrar el id del miembro ingresado 
![errorMemberNotFound](https://user-images.githubusercontent.com/81364315/188282479-bbc500df-f428-4b38-b11c-e5144c8433e5.png)

Error interno del servidor 
![memberErrorInternalServer](https://user-images.githubusercontent.com/81364315/188282485-71f77bfd-0b96-47c0-9eb1-c28d602d2034.png)

Se comento el paranoid para el correcto funcionamiento del endpoint, en caso de que se deba descomentar para que solo se actualice la columna deletedAt y no se elimine el registro, estoy al tanto para realizar el fix.

![memberModel](https://user-images.githubusercontent.com/81364315/188282607-aeedc800-9f8e-4c51-89ba-dfe820cbae4f.png)

2022-09-04 16:38 UTC, BrunoBohlmann requested changes
Fran, fijate que la ruta es para usuarios y pusiste el middleware isAdmin

2022-09-05 11:23 UTC, FerLeiva commented on routes/members.js
> +router.delete('/:id', isAuth, isAdmin, removeMember);
La validacion de admin no es necesaria

2022-09-05 11:23 UTC, FerLeiva commented on services/members.js
> +const memberRemoved = async (id) => {
deleteSingleMember puede ser un nombre mas apropiado

2022-09-05 11:23 UTC, FerLeiva commented on services/members.js
> +const list = async () => await Member.findAll();
Un nombre mas declarativo puede ser una mejora

2022-09-05 12:41 UTC, FranciscoLynch commented on services/members.js
> +const list = async () => await Member.findAll();
> Fran, fijate que la ruta es para usuarios y pusiste el middleware isAdmin

Perfecto, gracias por avisar. Copiar y pegar los middleware sin prestar atencion no es una buena practica.

2022-09-05 12:41 UTC, FranciscoLynch commented on services/members.js
> +const memberRemoved = async (id) => {
Genial, cambiado.

2022-09-05 12:42 UTC, FranciscoLynch commented on services/members.js
> +const list = async () => await Member.findAll();
> Un nombre mas declarativo puede ser una mejora

Lo copio. constante list cambiada a findAllMembers.

2022-09-05 12:56 UTC, FranciscoLynch commented
Conflictos resueltos. Quedo al pendiente de comentarios, cambios y/o de la aprobacion del PR.

2022-09-05 19:52 UTC, BrunoBohlmann approved these changes

2022-09-06 10:58 UTC, FerLeiva approved these changes

2022-09-06 10:58 UTC, merged