feat (OT267-25): endpoint registro de usuarios
alkemyTech/OT267-server pull request #8
Opened 2022-08-21 19:17 UTC by zayrarepositor

https://alkemy-labs.atlassian.net/browse/OT267-25 - Endpoint registro de usuarios

## Actions:
:bomb: bcryptjs and express-validator installed

:white_check_mark: post request for user creation
:white_check_mark: validations for firstName, lastName, email and password: 
  * firstName: required, length(1-15)  
  * lastName: required, length(1-15) 
  * email: required, unique, sanitization
  * password: length(min 8), uppercase(min 1), number(min 1), passwordConfirmation

:white_check_mark: encrypted password
:white_check_mark: user created as response

## Snips:
<p align='center'>user post</p>

![user post and password encrypt](https://user-images.githubusercontent.com/95602965/185806861-d6c2415f-860f-4d12-849c-7b21ce48f716.png)

<p align='center'>validations: required</p>

![2 -validation first name, lastname](https://user-images.githubusercontent.com/95602965/185806863-91e73c8e-1e4b-4cf7-84c1-6993b5c91389.png)

<p align='center'>validations 2:</p>

![3 - validation first name, lastname and email](https://user-images.githubusercontent.com/95602965/185806858-9f0d4f7a-c52f-466f-9fc0-43b82c125897.png)

<p align='center'>sanitization: mail</p>

![3 - sanitization email](https://user-images.githubusercontent.com/95602965/185806855-40865138-7562-4e4a-a419-294161d073ca.png)

<p align='center'>verification: unique mail</p>

![3 - validation mail unique](https://user-images.githubusercontent.com/95602965/185806860-cf1f03bd-d175-4499-a880-6edf05325cd3.png)

Good Life! ( ͡~ ͜ʖ ͡°)

2022-08-22 10:28 UTC, FerLeiva requested changes

2022-08-22 10:28 UTC, FerLeiva commented on package.json
> +    "name": "ong-server",
No deberias agregar este archivo al pull request

2022-08-22 17:29 UTC, zayrarepositor commented on package.json
> +    "name": "ong-server",
done

2022-08-23 15:48 UTC, FerLeiva commented
Zayra por favor resolve ese conflicto antes de hacer el marge. Gracias!

2022-08-23 16:27 UTC, zayrarepositor commented
Done! @FerLeiva

2022-08-23 16:57 UTC, merged