[OT267-77] Endpoint actualizar member
alkemyTech/OT267-server pull request #80
Opened 2022-09-08 20:36 UTC by AlfredoBlanco

https://alkemy-labs.atlassian.net/jira/software/c/projects/OT267/boards/362?modal=detail&selectedIssue=OT267-77
Así se veía la tabla antes : 
<img width="960" alt="All-members" src="https://user-images.githubusercontent.com/93164310/189220604-d42dcca9-429b-44ce-a50c-3b6fdbe6f22b.png">
Así cuando lo actualizas : 
<img width="960" alt="update-Member" src="https://user-images.githubusercontent.com/93164310/189220686-af98525a-c465-48e9-b9c2-3872ae6c0db5.png">
Así si no encuentra el id del member : 
<img width="960" alt="Error-Member" src="https://user-images.githubusercontent.com/93164310/189220750-45f31c5a-1a30-4b59-b9d4-daa54901b737.png">
 y por último, así se ve actualizada : 
<img width="960" alt="updated-members" src="https://user-images.githubusercontent.com/93164310/189220822-60f7102c-a6fd-4f91-ad0b-3f2357924317.png">

2022-09-09 12:27 UTC, FerLeiva commented on routes/testimonials.js
> +const express = require('express');
Este archivo por que esta aca?

2022-09-09 14:23 UTC, AlfredoBlanco commented on routes/testimonials.js
> +const express = require('express');
No tengo idea, cuando hice el pull me lo trajo, ahora lo elimino.

2022-09-09 16:40 UTC, EliasPedevilla commented on controllers/members.js
> +const { success, error, serverError } = require('../helpers/requestResponses');
Alfredo la idea de tener un index para los helpers es importarlos desde el index y asi si hay que importar varios herlpers se hace todo desde un mismo lugar.

2022-09-09 16:45 UTC, EliasPedevilla commented on services/members.js
> +    ...body,
aca creo que no hace falta el spread operator.

2022-09-09 16:47 UTC, EliasPedevilla commented on services/members.js
> +    ...body,
tampoco hace falta guardarlo en una constante si no haces nada con eso, podrias hacer un return directo asi como haces en el findAll

2022-09-09 16:53 UTC, EliasPedevilla requested changes
Alfredo. Ahi te hice unos comentarios en el codigo. Puedes revisarlos? 

- importacion de helpers desde el index
- no usar spread operator si no es necesario
-si se puede hacer un return directo no hace falta guardarlo en una constante
-Tambien fijate que estamos intentando usar updateSingleMember como nombre de funcion en el controlador y updateMember en el servicio.

2022-09-09 16:56 UTC, EliasPedevilla commented
Fijate tambien que los nombres de los commits describan los cambios que se hicieron y no ponerle a todos los commits el mismo nombre, ya que si se quiere buscar un estado anterior sera mas dificil encontrar cuando se hicieron los cambios.

2022-09-12 11:38 UTC, FerLeiva commented
Hola Alfre cuando puedas chequea los comentarios de Elias para que mandemos merge. Gracias!

2022-09-12 14:29 UTC, EliasPedevilla approved these changes

2022-09-12 17:58 UTC, FerLeiva approved these changes

2022-09-12 17:58 UTC, merged