[OT267-81] Endpoint listar comentarios
alkemyTech/OT267-server pull request #82
Opened 2022-09-09 15:06 UTC by AlfredoBlanco

https://alkemy-labs.atlassian.net/jira/software/c/projects/OT267/boards/362?modal=detail&selectedIssue=OT267-81&assignee=62fbebcb0268bddf1c915fcf
En la card pedía que estén ordenados por fecha de creación , interpreté que era de menor a mayor.
Así está la tabla : 
<img width="960" alt="Comments-menor-a-mayor" src="https://user-images.githubusercontent.com/93164310/189382163-8fb416d3-6363-47b7-91f7-9cbc543dbdfd.png">
Y así es lo que devuelve el endpoint, que pedía solo el body : 
<img width="960" alt="Comments-just-body" src="https://user-images.githubusercontent.com/93164310/189382288-6e200749-2e33-4c63-9f32-f493deb3628d.png">

2022-09-09 17:27 UTC, EliasPedevilla requested changes

2022-09-09 17:27 UTC, EliasPedevilla commented on services/comment.js
> +  const data = await Comment.findAll({});
Alfredo podes usar la opcion de sequelize order para no tener que hacerlo manualmente. Sequelize ya te devuelve las filas ordenadas segun el parametro que le pongas. 

puedes checkear la documentacion aqui: https://sequelize.org/docs/v6/core-concepts/model-querying-basics/#ordering

2022-09-12 11:38 UTC, FerLeiva commented
Hola Alfre cuando puedas chequea lo que te indica Elias para que mandemos merge. Gracias!

2022-09-12 14:44 UTC, EliasPedevilla approved these changes

2022-09-12 17:50 UTC, merged