[OT267-85] Endpoint para listar Comentarios en base a un post
alkemyTech/OT267-server pull request #89
Opened 2022-09-12 16:54 UTC by FranciscoLynch

Ticket: 
https://alkemy-labs.atlassian.net/jira/software/c/projects/OT267/boards/362?modal=detail&selectedIssue=OT267-85 

News Table and Comments Table
![newsAndCommentsTables](https://user-images.githubusercontent.com/81364315/189711722-ff567d57-d17e-4b85-9bdd-97bbd73e1c60.png)

Query success, list of all comments by new
![commentsByNewIdSuccess](https://user-images.githubusercontent.com/81364315/189711608-ce4d17e2-e217-4e95-bb53-54e0fc73b860.png) 

New not found 
![newIdNotFound](https://user-images.githubusercontent.com/81364315/189711887-4feb269a-48d1-4826-8a40-203fb8fc6703.png)

Server error 
![serverError](https://user-images.githubusercontent.com/81364315/189711947-57494b65-4963-4023-8713-6d80d2b2da93.png)

2022-09-12 18:02 UTC, FerLeiva requested changes

2022-09-12 18:02 UTC, FerLeiva commented on controllers/news.js
> +    if (!findNewByID) error({ res, message: 'new not found' });
Detalle de tipeo: En ingles no hay singular new de news, es una palabra que siempre se usa en plural!

2022-09-12 18:02 UTC, FerLeiva commented on controllers/news.js
> +    const findNewByID = await getNewById(id);
Lo mismo aca, el singular de news sigue siendo news

2022-09-12 18:02 UTC, FerLeiva commented on services/news.js
> -const paginator = async (req, model, urlmodel) => {
Estas borrando este comentario, eso esta ok?

2022-09-12 18:02 UTC, FerLeiva commented on services/news.js
> +const findAllCommentsByNewId = async (id) => {
News *

2022-09-12 18:06 UTC, FranciscoLynch commented on services/news.js
> -const paginator = async (req, model, urlmodel) => {
Por lo que me dijo Zay si, no hay problema.

2022-09-12 18:06 UTC, FranciscoLynch commented on controllers/news.js
> +    if (!findNewByID) error({ res, message: 'new not found' });
Ya lo cambio.

2022-09-12 18:06 UTC, FranciscoLynch commented on controllers/news.js
> +    const findNewByID = await getNewById(id);
Ya lo cambio.

2022-09-12 18:06 UTC, FranciscoLynch commented on services/news.js
> +const findAllCommentsByNewId = async (id) => {
Ya lo cambio.

2022-09-12 18:07 UTC, FerLeiva commented on services/news.js
> -const paginator = async (req, model, urlmodel) => {
Perfecto!

2022-09-12 18:08 UTC, FerLeiva commented
Fijate en todos lados donde ocurra lo de new, te marque los que llegue a ver

2022-09-12 19:59 UTC, AlfredoBlanco requested changes
Fran, fijate en la función que trae los comentarios que no hace falta usar la constante para luego devolverla, sino que directamente devolver la función.

2022-09-13 17:59 UTC, AlfredoBlanco approved these changes

2022-09-13 18:28 UTC, merged